#!/usr/bin/env Rscript
install.packages("vegan")
source("https://bioconductor.org/biocLite.R")
biocLite("BiocInstaller")
source("https://bioconductor.org/biocLite.R")
biocLite("philr")
source("https://bioconductor.org/biocLite.R")
biocLite("DECIPHER")
source("https://bioconductor.org/biocLite.R")
biocLite("phyloseq")
source("https://bioconductor.org/biocLite.R")
biocLite("Biostrings")
devtools::install_github("jbisanz/MicrobeR")
devtools::install_github("jbisanz/qiime2R")
